import "../../../fastlane/Fastfile"


CONSUME_SWIFT_PROJECT =  "demo_view_swift/#{SWIFT_PROJECT}"
CONSUME_OBJC_PROJECT = "demo_view_objc/#{OBJC_PROJECT}"

SWIFT_PROJECTS = [CONSUME_SWIFT_PROJECT]
OBJC_PROJECTS = [CONSUME_OBJC_PROJECT]
DEPLOYMENT_DEMO_PROJECTS = [CONSUME_SWIFT_PROJECT,CONSUME_OBJC_PROJECT]

def deployed_framework_version()
    path = "../#{IOS_FRAMEWORK_PLIST}"
    puts "deployed_framework_version path #{path}"
    framework_val("#{path}",'CFBundleShortVersionString')
end

def deployed_framework_build()
    path = "../#{IOS_FRAMEWORK_PLIST}"
    puts "#{path}"
    framework_val("#{path}",'CFBundleVersion')
end


lane :sync_project_version_numbers do
    sh("pwd")
    _version = deployed_framework_version()
    _build = deployed_framework_build()
    puts "$CONSUME_SWIFT_PROJECT"
    puts "$CONSUME_OBJC_PROJECT"
    DEPLOYMENT_DEMO_PROJECTS.each do |project|
        puts "$project"
        increment_version_number(xcodeproj:project,version_number:_version)
        increment_build_number(xcodeproj:project,build_number:_build)
    end
end

lane :test_projects do
    OBJC_PROJECTS.each do |project| 
		xcbuild(project:project,scheme: "VPKitDemo")
    end
    
    SWIFT_PROJECTS.each do |project|
		xcbuild(project:project,scheme: "VPKitDemoSwift")
    end
end


lane :pre_deploy do
    prepare(branch: "develop")
end

lane :deploy_to_cocoapods do
    xcversion(version: "11.6")
    ensure_xcode_version(version: "11.6")
    sh("pod trunk push '../VPKit.podspec' --verbose --allow-warnings")
end

lane :publish_and_deploy do
    sync_project_version_numbers	
    test_projects    
    sync_podspec_version(version:deployed_framework_version())
    git_commit(path:".", message: "deployed - v #{deployed_framework_version()}")
    add_git_tag(tag:"#{deployed_framework_version()}")
    push_to_git_remote
    deploy_to_cocoapods
end



lane :deploy do
    pre_deploy
    post_publish
end

lane :finished	 do

end

lane :temp do
    sh("pwd")
    _version = deployed_framework_version()

    _build = deployed_framework_build()
    puts "#{_version}  #{_build}"
end

